# Generated by Django 5.1.15 on 2026-07-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml", "0007_auto_20240314_1957"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlbackend",
            name="is_local",
            field=models.BooleanField(
                default=False,
                help_text="Used to run the model locally. If true, model runs locally.",
                verbose_name="is_local",
            ),
        ),
    ]
