# Generated by Django 5.1.15 on 2026-07-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0061_task_project_file_upload_idx_async"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="exclude_from_export",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="If true, this task will be excluded from exports",
                verbose_name="exclude from export",
            ),
        ),
    ]
