# Generated by Django 5.1.15 on 2026-07-14 09:13

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0062_task_exclude_from_export"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskGeoreferencing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, help_text="WGS84 [deg]", null=True),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, help_text="WGS84 [deg]", null=True),
                ),
                (
                    "altitude",
                    models.FloatField(
                        blank=True, help_text="절대고도(타원체고) [m]", null=True
                    ),
                ),
                (
                    "relative_height",
                    models.FloatField(
                        blank=True, help_text="이륙점 기준 상대고도 [m]", null=True
                    ),
                ),
                (
                    "yaw",
                    models.FloatField(
                        blank=True, help_text="짐벌 yaw [deg], 북 기준 시계+", null=True
                    ),
                ),
                (
                    "pitch",
                    models.FloatField(
                        blank=True, help_text="짐벌 pitch [deg], nadir=-90", null=True
                    ),
                ),
                (
                    "roll",
                    models.FloatField(
                        blank=True, help_text="짐벌 roll [deg]", null=True
                    ),
                ),
                (
                    "flight_yaw",
                    models.FloatField(
                        blank=True, help_text="기체 yaw [deg] — 짐벌과 별도", null=True
                    ),
                ),
                (
                    "ground_alt",
                    models.FloatField(
                        blank=True, help_text="지면 절대고도 [m]", null=True
                    ),
                ),
                (
                    "ground_alt_source",
                    models.CharField(
                        choices=[
                            ("lrf", "Laser Range Finder (실측)"),
                            ("relative", "AbsoluteAlt - RelativeAlt"),
                            ("dem", "DEM lookup"),
                            ("none", "Unknown"),
                        ],
                        default="none",
                        help_text="LRF 실측이 relative 역산보다 정확 — 우선 사용",
                        max_length=8,
                    ),
                ),
                (
                    "rtk_flag",
                    models.IntegerField(
                        blank=True,
                        help_text="DJI RtkFlag: 0=GPS only, 16=Float, 50=Fixed(신뢰 가능)",
                        null=True,
                    ),
                ),
                (
                    "rtk_std_lat",
                    models.FloatField(blank=True, help_text="[m]", null=True),
                ),
                (
                    "rtk_std_lon",
                    models.FloatField(blank=True, help_text="[m]", null=True),
                ),
                (
                    "rtk_std_hgt",
                    models.FloatField(blank=True, help_text="[m]", null=True),
                ),
                (
                    "captured_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="촬영시각 — RGB/IR 페어링·시계열 추적의 기준",
                        null=True,
                    ),
                ),
                (
                    "camera_model",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "modality",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="wide | zoom | ir (파일명 접미사 _W/_Z/_T 기반)",
                        max_length=8,
                    ),
                ),
                ("focal_length_mm", models.FloatField(blank=True, null=True)),
                (
                    "focal_length_35mm",
                    models.IntegerField(
                        blank=True,
                        help_text="35mm 환산 — FOV/footprint 계산 입력",
                        null=True,
                    ),
                ),
                ("image_width", models.IntegerField(blank=True, null=True)),
                ("image_height", models.IntegerField(blank=True, null=True)),
                (
                    "image_sha1",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="파일 SHA-1 (metadata.py 컨벤션) — SQLite 인덱스와 조인 키",
                        max_length=40,
                    ),
                ),
                (
                    "ground_sample_distance",
                    models.FloatField(blank=True, help_text="GSD [m/px]", null=True),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("RTK", "RTK"),
                            ("PPK", "PPK"),
                            ("GCP", "GCP-based"),
                            ("NONE", "None"),
                        ],
                        default="NONE",
                        max_length=8,
                    ),
                ),
                (
                    "accuracy_m",
                    models.FloatField(
                        blank=True, help_text="추정 수평 정확도 [m]", null=True
                    ),
                ),
                (
                    "offset_correction",
                    models.JSONField(
                        blank=True,
                        help_text="RGB-IR co-registration 보정값 (고도/자세 의존 affine)",
                        null=True,
                    ),
                ),
                (
                    "transform_matrix",
                    models.JSONField(
                        blank=True, help_text="픽셀→지리 변환 행렬", null=True
                    ),
                ),
                (
                    "raw_metadata",
                    models.JSONField(
                        blank=True,
                        help_text="ImageMetadata.to_dict() 전체 — 재계산/디버깅용 원본 보존",
                        null=True,
                    ),
                ),
                (
                    "footprint_rgb",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True,
                        help_text="RGB 지면 커버리지 (핀홀 광선-지면 교차, 원본 좌표)",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "footprint_ir",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True,
                        help_text="IR 커버리지 — 광학축 오프셋/FOV가 달라 RGB와 별도",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "footprint_rgb_corrected",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True,
                        help_text="GeoAlignmentCorrection 반영본 — 공간 검색은 이 컬럼 사용",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "footprint_ir_corrected",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "footprint_low_confidence",
                    models.BooleanField(
                        default=False,
                        help_text="near-horizon clamp 등으로 footprint 신뢰 낮음",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending extraction"),
                            ("completed", "Completed"),
                            ("no_gps", "No GPS metadata"),
                            ("unpaired", "RGB/IR pair not found"),
                            ("failed", "Extraction failed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="비동기 EXIF/XMP 추출 상태",
                        max_length=16,
                    ),
                ),
                (
                    "extractor_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="추출 로직 버전 — 업그레이드 후 선별 재계산 대상 조회용",
                        max_length=16,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", help_text="status=failed일 때 원인"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.OneToOneField(
                        help_text="1:1 대상 task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="georeferencing",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "db_table": "task_georeferencing",
                "indexes": [
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["footprint_rgb_corrected"],
                        name="taskgeo_fp_rgb_corr_gist",
                    ),
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["footprint_ir_corrected"],
                        name="taskgeo_fp_ir_corr_gist",
                    ),
                    models.Index(
                        fields=["status", "extractor_version"],
                        name="taskgeo_status_ver",
                    ),
                    models.Index(
                        fields=["modality", "captured_at"], name="taskgeo_modality_time"
                    ),
                ],
            },
        ),
    ]
